module.exports = (req, res, next) => {
    res.data.path = '/movie';
    res.data.context = {
        "language_name": "Español latino",
        "language_iso": "es-MX",
        "site_keywords": {
            "movie_link": "latino/pelicula-completa",
            "home_title": "Películas completas con audio latino"
        },
        "site": {
            "title": "Ver Película Los increibles 2 (2018) Español latino Online Gratis - REPELIS",
            "description": "Ver película Los increibles 2 (2018) - Helen debe liderar una campaña a fin de que los superhéroes retornen, mientras que Bob vive su vida \"normal\" con Violet, Dash y el bebé Jack-Jack. Su misión se marcha a pique cuando aparece un nuevo villano con ...",
            "canonical": "https://www.repelis.biz/latino/pelicula-completa/2018/los-increibles-2/",
            "analytics": "UA-130039796-1",
            "header_links": [{
                    "display_name": "Acción",
                    "link": "/categoria/accion/",
                    "index": 1,
                    "total": 3,
                    "isFirst": true,
                    "isLast": false
                },
                {
                    "display_name": "Terror",
                    "link": "/categoria/terror/",
                    "index": 2,
                    "total": 3,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "display_name": "Animación",
                    "link": "/categoria/animacion/",
                    "index": 3,
                    "total": 3,
                    "isFirst": false,
                    "isLast": true
                }
            ],
            "footer_links": [{
                    "display_name": "Acción",
                    "link": "/categoria/accion/",
                    "index": 1,
                    "total": 2,
                    "isFirst": true,
                    "isLast": false
                },
                {
                    "display_name": "Terror",
                    "link": "/categoria/terror/",
                    "index": 2,
                    "total": 2,
                    "isFirst": false,
                    "isLast": true
                }
            ],
            "search_action": "/busqueda/"
        },
        "featured_movies": [{
                "hash": "animales-fantasticos-los-crimenes-de-grindelwald",
                "title": "Animales fantásticos: Los crímenes de Grindelwald",
                "overview": "Al final de la primera película, el poderoso mago obscuro Gellert Grindelwald (Johnny Depp) fue capturado por MACUSA (Congreso Mágico de los U.S.A. de América), con la ayuda de Newt Scamander (Eddie Redmayne). Mas, cumpliendo con su amenaza, Grindelwald escapó de su custodia y ha empezado a reunir seguidores, la mayor parte de los que no sospechan sus auténticas intenciones: levantar a los magos purasangre para reinar sobre todas y cada una de las criaturas no mágicas. En un sacrificio por frustrar los planes de Grindelwald, Albus Dumbledore (Jude Law) recluta a su viejo estudiante Newt Scamander, quien accede a prestar su ayuda, sin conocer los riesgos que esperan. Las líneas quedan marcadas mientras que el amor y la fidelidad son puestos a prueba, aun entre los amigos más próximos y la familia, en un planeta mágico poco a poco más dividido.",
                "poster_path": "/uyJgTzAsp3Za2TaPiZt2yaKYRIR.jpg",
                "release_date": "2018-11-14T03:00:00.000Z",
                "vote_average": 7.4,
                "release_year": 2018,
                "release_month": 11,
                "release_day": 14,
                "link": "/latino/pelicula-completa/2018/animales-fantasticos-los-crimenes-de-grindelwald/",
                "index": 1,
                "total": 8,
                "isFirst": true,
                "isLast": false
            },
            {
                "hash": "el-grinch",
                "title": "El Grinch",
                "overview": "Nueva adaptación de la historia de doctor Seuss que cuenta la historia de un insolente pulguillas que se plantea hurtar la Navidad hasta el momento en que el exuberante espíritu navideño de una pequeña le procura hacer cambiar de parecer.",
                "poster_path": "/lK3BZcdmfQWvOSQeJa6Oes79LXB.jpg",
                "release_date": "2018-11-08T03:00:00.000Z",
                "vote_average": 6.8,
                "release_year": 2018,
                "release_month": 11,
                "release_day": 8,
                "link": "/latino/pelicula-completa/2018/el-grinch/",
                "index": 2,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "bohemian-rhapsody",
                "title": "Bohemian Rhapsody",
                "overview": "Bohemian Rhapsody es una definitiva y sonora celebración de Queen, de su música y de su excepcional vocalista Freddie Mercury, que desafió estereotipos y también hizo añicos tradiciones para transformarse en uno de los showmans más queridos del planeta. La película plasma el meteórico ascenso al olimpo de la música de la banda por medio de sus icónicas canciones y su revolucionario sonido, su crisis cuando el modo de vida de Mercury estuvo fuera de control, y su triunfante asamblea en la víspera del Live Aid, en la que Mercury, mientras que padecía una enfermedad que conminaba su vida, lidera a la banda en uno de los conciertos de rock más grandes de la historia. Vamos a ver de qué manera se basó el legado de una banda que siempre y en todo momento se pareció más a una familia, y que prosigue inspirando a propios y extraños, soñadores y amantes de la música hasta nuestros días.",
                "poster_path": "/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
                "release_date": "2018-10-24T03:00:00.000Z",
                "vote_average": 8.3,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 24,
                "link": "/latino/pelicula-completa/2018/bohemian-rhapsody/",
                "index": 3,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "kung-fu-league",
                "title": "Kung Fu League",
                "overview": "Comedia de artes marciales siguiendo a un conjunto de leyendas del kung fu que se unen para enfrentar a los malos. Las leyendas incluyen a VINCENT ZHAO repitiendo su papel como \"Wong Fei Hung\" con DENNIS TO, de nuevo interpretando al \"Wing Chun\" profesor \"Ip Man\", DANNY CHAN KWOK KWAN KWAN como \"Chen Zhen\" y ANDY ON como profesor \"Huo Yuan Jia\".",
                "poster_path": "/rW0A73hjzPWVwADlCTLnjLhAFLX.jpg",
                "release_date": "2018-10-19T03:00:00.000Z",
                "vote_average": 4.3,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 19,
                "link": "/latino/pelicula-completa/2018/kung-fu-league/",
                "index": 4,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "la-noche-de-halloween",
                "title": "La noche de Halloween",
                "overview": "Jamie Lee Curtis retorna a su papel icónico como Laurie Strode, quien llega a su enfrentamiento final con Michael Myers, la figura enmascarada que la ha perseguido desde el momento en que escapó por poco de su fiesta de asesinatos en la noche de Halloween de hace 4 décadas. Esta película, la undécima película de la serie \"Halloween\", ignorará los acontecimientos de todas y cada una de las secuelas precedentes, reanudando cuarenta años tras los acontecimientos de la película original.",
                "poster_path": "/bXs0zkv2iGVViZEy78teg2ycDBm.jpg",
                "release_date": "2018-10-18T03:00:00.000Z",
                "vote_average": 6.5,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 18,
                "link": "/latino/pelicula-completa/2018/la-noche-de-halloween/",
                "index": 5,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "overlord",
                "title": "Overlord",
                "overview": "La víspera del Día D, un conjunto de soldados aliados es mandado a la Francia ocupada para llenar una misión esencial para la victoria. Sobre el terreno, descubren un laboratorio en el que se realizan desatinados ensayos. La capacitación que han recibido no les ha listo para enfrentarse a soldados manipulados genéticamente. Overlord se aúna a la insigne lista de producciones de Bad Robot, la revolucionaria compañía de J. J. Abrams.",
                "poster_path": "/l76Rgp32z2UxjULApxGXAPpYdAP.jpg",
                "release_date": "2018-10-10T03:00:00.000Z",
                "vote_average": 6.9,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 10,
                "link": "/latino/pelicula-completa/2018/overlord/",
                "index": 6,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "venom",
                "title": "Venom",
                "overview": "Venom es un spin-off de uno de los villanos más conocidos del Cosmos Marvel. Producida por Sony, esta película se va a centrar en uno de los mayores oponentes de Peter Parker, teniendo al villano de Spider-Man tres como protagonista del filme, que está interpretado por Tom Hardy. Venom vive en Eddie Brock, un viejo y respetado cronista que, tras perderlo todo a nivel profesional, y también incitado por su odio cara Spider-Man decidió dejar que el simbionte se introdujera en él. La película sobre el personaje creado por David Micheliene y Todd McFarlane, está producida por Avid Labrad, Matthew Tolmach y Amy Pascal, dirigida por Ruben Fleischer (Bienvenidos a Zombieland) y escrita por Scott Rosenberg (Alta lealtad) y Jeff Pinkner (The Amazing Spider-Man 2: El poder de Electro).",
                "poster_path": "/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
                "release_date": "2018-10-03T03:00:00.000Z",
                "vote_average": 6.6,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 3,
                "link": "/latino/pelicula-completa/2018/venom/",
                "index": 7,
                "total": 8,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "nace-una-estrella",
                "title": "Nace una estrella",
                "overview": "Jackson Maine es una estrella de la música que se enamora de Ally (Lady Gaga), una artista que lucha por salir adelante. Justo cuando Ally está a puntito de desamparar su sueño de transformarse en vocalista, Jack decide asistirla en su carrera cara la fama. El camino va a ser más duro de lo que imaginan ...",
                "poster_path": "/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
                "release_date": "2018-10-03T03:00:00.000Z",
                "vote_average": 7.5,
                "release_year": 2018,
                "release_month": 10,
                "release_day": 3,
                "link": "/latino/pelicula-completa/2018/nace-una-estrella/",
                "index": 8,
                "total": 8,
                "isFirst": false,
                "isLast": true
            },
            {
                "hash": "el-depredador",
                "title": "El depredador",
                "overview": "Desde los límites del espacio hasta los suburbios de las pequeñas urbes, la busca llega a la casa de la reinvención por Shane Black de la saga \"Predator\". Ahora, los cazadores más mortales del cosmos son más fuertes, más inteligentes y más mortales que jamás, y se han mejorado genéticamente con ADN de otras especies. En el momento en que un pequeño accidentariamente desencadena su regreso a la Tierra, solo un conjunto de ex- soldados y una maestra de ciencias van a poder eludir, quizás el fin de la raza humana...",
                "poster_path": "/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg",
                "release_date": "2018-09-13T03:00:00.000Z",
                "vote_average": 5.3,
                "release_year": 2018,
                "release_month": 9,
                "release_day": 13,
                "link": "/latino/pelicula-completa/2018/el-depredador/",
                "index": 1,
                "total": 24,
                "isFirst": true,
                "isLast": false
            },
            {
                "hash": "la-monja",
                "title": "La monja",
                "overview": "En el momento en que una joven monja se suicida en una abadía de clausura en Rumanía, un sacerdote especialista en posesiones demoniacas y una novicia a puntito de tomar sus votos, son mandados por el Vaticano para investigar. Juntos descubren el profano secreto de la orden. Exponiendo no solo sus vidas sino más bien su fe y hasta sus ánimas, se encaran a una fuerza maléfica en forma de monja mefistofélica, en una abadía que se transforma en un campo de batalla de horror entre los vivos y los condenados.... Spin-off de la película de terror de dos mil dieciseis 'The Conjuring 2'. Producida por Atomic Monster, productora del directivo experto en el género de terror, James Wan.",
                "poster_path": "/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg",
                "release_date": "2018-09-05T03:00:00.000Z",
                "vote_average": 5.7,
                "release_year": 2018,
                "release_month": 9,
                "release_day": 5,
                "link": "/latino/pelicula-completa/2018/la-monja/",
                "index": 2,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "el-legado",
                "title": "El legado",
                "overview": "Perseguidos por un delincuente vengativo (James Franco) y una banda de soldados sobrenaturales, un ex--convicto recién liberado (Jack Reynor) y su hermano adolescente adoptivo (Myles Truitt) se ven forzados a escapar con una arma de origen enigmático que es su única protección.",
                "poster_path": "/9qYKrgzHbYtKej9Gvd7NxJvGiC2.jpg",
                "release_date": "2018-08-29T03:00:00.000Z",
                "vote_average": 6.4,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 29,
                "link": "/latino/pelicula-completa/2018/el-legado/",
                "index": 3,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "searching",
                "title": "Buscando...",
                "overview": "Una vez que la hija de dieciseis años de David Kim desaparece, se abre una investigación policial. Mas treinta y siete horas después y sin una sola pista, David decide buscar en el único sitio donde absolutamente nadie ha buscado aún y donde se guardan todos y cada uno de los secretos el día de hoy en día: el PC portátil de su hija. David debe rastrear las huellas digitales de su hija antes que desaparezca por siempre. Un thriller que se desarrolla en la pantalla del PC.",
                "poster_path": "/pk9R56ZFlofbBzfwBnHlDyg5DMs.jpg",
                "release_date": "2018-08-24T03:00:00.000Z",
                "vote_average": 7.7,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 24,
                "link": "/latino/pelicula-completa/2018/searching/",
                "index": 4,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "the-seven-deadly-sins-prisioneros-del-cielo",
                "title": "The Seven Deadly Sins: Prisioneros del Cielo",
                "overview": "Viajando en busca del ingrediente extraño, \"pez cielo\" Meliodas y Hawk llegan a un palacio que flota sobre las nubes. La gente de allá está ocupada preparando una liturgia, destinada a resguardar su hogar de una fiero bestia que se lúcida una vez cada tres mil años. Mas antes que se complete el ritual, los 6 Caballeros de Negro, un ejército del Clan Diablo, quitan el sello a la bestia y conminan la vida de todos en el Palacio del Cielo.",
                "poster_path": "/lgYGPujZNckyKwQQNwMLmkWoKui.jpg",
                "release_date": "2018-08-18T03:00:00.000Z",
                "vote_average": 5.6,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 18,
                "link": "/latino/pelicula-completa/2018/the-seven-deadly-sins-prisioneros-del-cielo/",
                "index": 5,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "alpha",
                "title": "Alfa",
                "overview": "Una aventura épica ambientada en la última Edad de Hielo, ALPHA cuenta una historia alucinante y visualmente deslumbrante que lanza luz sobre los orígenes del mejor amigo del hombre. Mientras que estaba en su primera cacería con el conjunto más elitista de su tribu, un joven se lesiona y debe aprender a subsistir solo en el desierto. De mala gana amaestrando a un lobo solitario descuidado por su manada, la pareja aprende a confiar el uno en el otro y se transforman en aliados poco probables, aguantando incontables riesgos y apabullantes probabilidades de hallar el camino a casa antes que llegue el invierno.",
                "poster_path": "/afdZAIcAQscziqVtsEoh2PwsYTW.jpg",
                "release_date": "2018-08-17T03:00:00.000Z",
                "vote_average": 5.5,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 17,
                "link": "/latino/pelicula-completa/2018/alpha/",
                "index": 6,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "milla-22-el-escape",
                "title": "Milla 22: el escape",
                "overview": "James Silva (Mark Wahlberg) es un experimentado agente de la CIA, mandado a un país sospechoso de actividad nuclear ilegal. Cuando el funcionario local, LI (Iko Uwais), llega a la embajada de los EE. UU. buscando intercambiar información sobre material radiactivo robado a cambio de su paso seguro a los EE. UU., Silva tiene la labor de transportarlo desde el centro de una urbe, en una peligrosa misión, hasta una pista de aterrizaje a veintidos millas de distancia.",
                "poster_path": "/2L8ehd95eSW9x7KINYtZmRkAlrZ.jpg",
                "release_date": "2018-08-16T03:00:00.000Z",
                "vote_average": 5.8,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 16,
                "link": "/latino/pelicula-completa/2018/milla-22-el-escape/",
                "index": 7,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "locamente-millonarios",
                "title": "Locamente millonarios",
                "overview": "Rachel Chu es maestra de economía en la Universidad de la ciudad de Nueva York, allá conoce a Nick Young -maestro de historia- y se enamoran. Los dos deben viajar a la urbe natal de Nick, Singapur, para acudir a la boda de su mejor amigo. Es allá cuando Rachel descubre que su novio pertenece a una de las familias más ricas de Asia y que todas y cada una de las solteras de clase alta están impresionantemente recelosas de ella. La joven deberá enfrentarse a todas y cada una  y probar a la familia de su novio que  asimismo es digna de estar con él.",
                "poster_path": "/gnTqi4nhIi1eesT5uYMmhEPGNih.jpg",
                "release_date": "2018-08-15T03:00:00.000Z",
                "vote_average": 7,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 15,
                "link": "/latino/pelicula-completa/2018/locamente-millonarios/",
                "index": 8,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "megalodon",
                "title": "Megalodón",
                "overview": "Un sumergible de aguas profundas que es parte de un programa internacional de vigilancia submarina, ha sido atacado por una gran criatura que se creía extinta. Ahora está estropeado en el fondo de la fosa oceánica más profunda del Pacífico con su tripulación atrapada en el interior. El tiempo se termina y, contra los deseos de su hija Suyin (Li Bingbing), un soñador oceanógrafo chino (Winston Adiós) contrata a Jonas Taylor (Jason Statham), un especialista en rescate en aguas profundas. Su misión va a ser salvar a la tripulación y asimismo al océano de una amenaza imparable: un tiburón prehistórico de veintitres metros conocido con el nombre de Megalodón.",
                "poster_path": "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
                "release_date": "2018-08-09T03:00:00.000Z",
                "vote_average": 6,
                "release_year": 2018,
                "release_month": 8,
                "release_day": 9,
                "link": "/latino/pelicula-completa/2018/megalodon/",
                "index": 9,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "el-infiltrado-del-kkklan",
                "title": "El infiltrado del KKKlan",
                "overview": "A inicios de los años setenta, una temporada de gran agitación social con la encarnizada lucha por los derechos civiles como telón de fondo, Ron Stallworth se transforma en el primer detective negro del departamento de policía de Rojo Springs, mas es recibido con escepticismo y hostilidad por los mandos y los agentes. Sin amedrentarse, decide proseguir adelante y hacer algo por su comunidad haciendo una misión muy peligrosa: infiltrarse en el Ku Klux Klan y exponerlo frente a la urbe.",
                "poster_path": "/55W6mUVv4CXMMQHHhV2zXtLSpXQ.jpg",
                "release_date": "2018-07-30T03:00:00.000Z",
                "vote_average": 7.4,
                "release_year": 2018,
                "release_month": 7,
                "release_day": 30,
                "link": "/latino/pelicula-completa/2018/el-infiltrado-del-kkklan/",
                "index": 10,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "el-justiciero-2",
                "title": "El justiciero 2",
                "overview": "Robert McCall,  hace justicia a los explotados y oprimidos, mas ahora se embarca en una infatigable busca de venganza por el planeta cuando se entera de que asesinaron a una novia que tuvo hace mucho.",
                "poster_path": "/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg",
                "release_date": "2018-07-19T03:00:00.000Z",
                "vote_average": 6.2,
                "release_year": 2018,
                "release_month": 7,
                "release_day": 19,
                "link": "/latino/pelicula-completa/2018/el-justiciero-2/",
                "index": 11,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "mision-imposible-6-repercusion",
                "title": "Misión imposible 6: Repercusión",
                "overview": "A veces, hasta las mejores pretensiones pueden volverse contra nosotros. En “MISIÓN: IMPOSIBLE – FALLOUT” nos hallamos a Ethan Hunt (Tom Cruise) y su equipo en el Fondo Monetario Internacional (Alec Baldwin, Simon Pegg, Ving Rhames), conjuntamente con ciertos aliados conocidos (Rebecca Ferguson, Michelle Monaghan) en una carrera contrarreloj tras una misión errada. Henry Cavill, Angela Bassett y Vanessa Kirby asimismo se unen al activo reparto, al tiempo que el directivo Christopher McQuarrie vuelve a ponerse al timón.",
                "poster_path": "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
                "release_date": "2018-07-13T03:00:00.000Z",
                "vote_average": 7.3,
                "release_year": 2018,
                "release_month": 7,
                "release_day": 13,
                "link": "/latino/pelicula-completa/2018/mision-imposible-6-repercusion/",
                "index": 12,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "rascacielos-rescate-en-las-alturas",
                "title": "Rascacielos: Rescate en las alturas",
                "overview": "Will Sawyer, viejo líder del Equipo de Rescate de Rehenes del FBI y veterano de guerra del ejército de E.U., ahora se hace cargo de valorar la seguridad de los rascacielos. A lo largo de un viaje de trabajo en China, se ve incriminado en el incendio del edificio más alto y seguro del planeta. Perseguido y a la fuga, Will va a deber hallar a los que le han tendido la trampa, adecentar su nombre y salvar a su familia, atrapada dentro del rascacielos… sin ceder a las llamas.",
                "poster_path": "/5LYSsOPzuP13201qSzMjNxi8FxN.jpg",
                "release_date": "2018-07-11T03:00:00.000Z",
                "vote_average": 6.1,
                "release_year": 2018,
                "release_month": 7,
                "release_day": 11,
                "link": "/latino/pelicula-completa/2018/rascacielos-rescate-en-las-alturas/",
                "index": 13,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "ant-man-y-la-avispa",
                "title": "Ant-Man y la avispa",
                "overview": "Tras \"Capitán América: Guerra Civil\", Scott Lang lidia con las consecuencias de sus elecciones como superhéroe y padre. Mientras que lucha por sostener un equilibrio entre su vida hogareña y sus responsabilidades como Ant-Man, se encara a Hope van Dyne y al doctor Hank Pym con una nueva misión urgente. Scott debe regresar a ponerse el traje y aprender a batallar así como La Avispa mientras que el equipo trabaja en conjunto para descubrir secretos del pasado.",
                "poster_path": "/rv1AWImgx386ULjcf62VYaW8zSt.jpg",
                "release_date": "2018-07-04T03:00:00.000Z",
                "vote_average": 6.9,
                "release_year": 2018,
                "release_month": 7,
                "release_day": 4,
                "link": "/latino/pelicula-completa/2018/ant-man-y-la-avispa/",
                "index": 14,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "los-increibles-2",
                "title": "Los increibles 2",
                "overview": "Helen debe liderar una campaña a fin de que los superhéroes retornen, mientras que Bob vive su vida \"normal\" con Violet, Dash y el bebé Jack-Jack. Su misión se marcha a pique cuando aparece un nuevo villano con un refulgente plan que lo amenaza todo. Mas los Parr no se asustarán y menos teniendo a Frozono de su parte.",
                "poster_path": "/x1txcDXkcM65gl7w20PwYSxAYah.jpg",
                "release_date": "2018-06-14T03:00:00.000Z",
                "vote_average": 7.6,
                "release_year": 2018,
                "release_month": 6,
                "release_day": 14,
                "link": "/latino/pelicula-completa/2018/los-increibles-2/",
                "index": 15,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "deadpool-2",
                "title": "Deadpool 2",
                "overview": "Wade Wilson (Ryan Reynolds), mejor conocido como Deadpool, su nombre de batalla y también identidad antiheroica, está de regreso con Deadpool dos y esta vez su misión va a ser salvar a un chaval llamado Russell (Julian Dennison) de las manos de un poderoso contrincante llamado Cable (Josh Brolin). En interés de dar cumplimiento a su labor el antihéroe formará un conjunto al que va a poner el nombre de X-Force. Secuela de la triunfante película (colectó más de setecientos ochenta millones de dólares estadounidenses en el mundo entero) parodia de los superhéroes mutantes del dos mil dieciseis, asimismo protagonizada por Reynolds.",
                "poster_path": "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
                "release_date": "2018-05-15T03:00:00.000Z",
                "vote_average": 7.5,
                "release_year": 2018,
                "release_month": 5,
                "release_day": 15,
                "link": "/latino/pelicula-completa/2018/deadpool-2/",
                "index": 16,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "vengadores-infinity-war",
                "title": "Vengadores: Infinity War",
                "overview": "El todopoderoso Thanos ha despertado con la promesa de arrasar con todo a su paso, portando el Guantelete del Infinito, que le proporciona un poder inestimable. Los únicos capaces de pararle los pies son los Vengadores y el resto de superhéroes de la galaxia, que habrán de estar prestos a sacrificarlo todo por un bien mayor.",
                "poster_path": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                "release_date": "2018-04-25T03:00:00.000Z",
                "vote_average": 8.3,
                "release_year": 2018,
                "release_month": 4,
                "release_day": 25,
                "link": "/latino/pelicula-completa/2018/vengadores-infinity-war/",
                "index": 17,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "black-panther",
                "title": "Pantera Negra",
                "overview": "Pantera negra, de Marvel Studios, prosigue a T'Challa, quien retorna a Wakanda, su solitaria nación africana de tecnología avanzada, para aceptar como rey. Mas en el momento en que un viejo y poderoso oponente resurge, la fortaleza de T'Challa como rey y superhéroe es puesta a prueba cuando se ve implicado en un enorme enfrentamiento que pone bajo riesgo el destino de Wakanda y del planeta entero.",
                "poster_path": "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
                "release_date": "2018-02-13T03:00:00.000Z",
                "vote_average": 7.3,
                "release_year": 2018,
                "release_month": 2,
                "release_day": 13,
                "link": "/latino/pelicula-completa/2018/black-panther/",
                "index": 18,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "thor-ragnarok",
                "title": "Thor: Ragnarok",
                "overview": "Thor está preso del otro lado del cosmos sin su poderoso martillo y se encara a una carrera contra el tiempo. Su objetivo es regresar a Asgard y detener el Ragnarok por el hecho de que significaría la destrucción de su planeta natal y el fin de la civilización Asgardiana a manos de una todopoderosa y nueva amenaza, la inexorable Hela. Mas, primero va a deber subsistir a una competición mortal de gladiadores que lo encarará a su aliado y compañero en los Vengadores, ¡el Increíble Hulk!.",
                "poster_path": "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
                "release_date": "2017-10-25T03:00:00.000Z",
                "vote_average": 7.5,
                "release_year": 2017,
                "release_month": 10,
                "release_day": 25,
                "link": "/latino/pelicula-completa/2017/thor-ragnarok/",
                "index": 19,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "animales-fantasticos-y-donde-encontrarlos",
                "title": "Animales fantásticos y dónde encontrarlos",
                "overview": "Newt Scamander llega al Congreso Mágico de los Estados Unidos de América con un maletín mágicamente expandido, que alberga varias criaturas peligrosas y sus hábitats. Cuando las criaturas escapan del maletín, envía a las autoridades mágicas americanas después de Newt, y amenaza con forzar aún más el estado de las relaciones mágicas y no mágicas.",
                "poster_path": "/1M91Bt3oGspda75H9eLqYZkJzgO.jpg",
                "release_date": "2016-11-16T03:00:00.000Z",
                "vote_average": 7.3,
                "release_year": 2016,
                "release_month": 11,
                "release_day": 16,
                "link": "/latino/pelicula-completa/2016/animales-fantasticos-y-donde-encontrarlos/",
                "index": 20,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "los-ilusionistas-2",
                "title": "Los ilusionistas 2",
                "overview": "Un año después de engañar al FBI y ganar la adulación del público con sus espectáculos de magia al estilo Robin Hood, Los Cuatro Jinetes reaparecen en una actuación aún más impresionante con la esperanza de exponer las prácticas poco éticas de un magnate de la tecnología. El hombre detrás de su acto de desaparición no es otro que Walter Mabry, un prodigio en la tecnología que pone en peligro a los Jinetes y los lleva a cometer un asalto aún más peligroso. Su única esperanza es llevar a cabo un último truco sin precedentes para limpiar sus nombres y revelar la mente maestra detrás de todo.",
                "poster_path": "/hU0E130tsGdsYa4K9lc3Xrn5Wyt.jpg",
                "release_date": "2016-06-02T03:00:00.000Z",
                "vote_average": 6.8,
                "release_year": 2016,
                "release_month": 6,
                "release_day": 2,
                "link": "/latino/pelicula-completa/2016/los-ilusionistas-2/",
                "index": 21,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "maze-runner-el-corredor-del-laberinto",
                "title": "Maze Runner: El corredor del laberinto",
                "overview": "Thomas abre los ojos y se da cuenta que está en un ascensor. Lo extraño es que no recuerda nada, ni dónde está, ni quién es. Lo único que aún permanece intacto en su memoria es su nombre, y ya es mucho. Antes de que le dé tiempo a cuestionarse algo sobre sí mismo las puertas se abrirán y aparecerá ante él un extraño mundo. Todo lo que ve son chicos de su edad que tienen su mismo estado de amnesia. Una aventura fantástica que pronto destapará la dura realidad bajo ese velo de incertidumbre.",
                "poster_path": "/coss7RgL0NH6g4fC2s5atvf3dFO.jpg",
                "release_date": "2014-09-10T03:00:00.000Z",
                "vote_average": 7.1,
                "release_year": 2014,
                "release_month": 9,
                "release_day": 10,
                "link": "/latino/pelicula-completa/2014/maze-runner-el-corredor-del-laberinto/",
                "index": 22,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "piratas-del-caribe-la-maldicion-del-perla-negra",
                "title": "Piratas del Caribe: La maldición del Perla Negra",
                "overview": "Mar Caribe, siglo XVIII. El aventurero capitán Jack Sparrow piratea en aguas caribeñas, pero su andanzas terminan cuando su enemigo, el Capitán Barbossa, después de robarle su barco, el Perla Negra, ataca la ciudad de Port Royal y secuestra a Elizabeth Swann, la hija del Gobernador. Will Turner, amigo de la infancia de Elizabeth, se une a Jack para rescatarla y recuperar el Perla Negra. Pero Barbossa y su tripulación son víctimas de un conjuro que los condena a vivir eternamente y a transformarse cada noche en esqueletos vivientes. El conjuro sólo puede romperse si devuelven una pieza de oro azteca y saldan una deuda de sangre. El rescate de la bella Elizabeth será una tarea difícil, pues la maldición es real y será difícil enfrentarse con quienes no pueden morir.",
                "poster_path": "/tkt9xR1kNX5R9rCebASKck44si2.jpg",
                "release_date": "2003-07-09T03:00:00.000Z",
                "vote_average": 7.6,
                "release_year": 2003,
                "release_month": 7,
                "release_day": 9,
                "link": "/latino/pelicula-completa/2003/piratas-del-caribe-la-maldicion-del-perla-negra/",
                "index": 23,
                "total": 24,
                "isFirst": false,
                "isLast": false
            },
            {
                "hash": "harry-potter-y-la-piedra-filosofal",
                "title": "Harry Potter y la piedra filosofal",
                "overview": "El día en que cumple once años, Harry Potter se entera de que es hijo de dos destacados hechiceros, de los que ha heredado poderes mágicos. En la escuela Hogwarts de Magia y Hechicería, donde se educa con otros niños que también tienen poderes especiales, aprenderá todo lo necesario para ser mago.",
                "poster_path": "/dCtFvscYcXQKTNvyyaQr2g2UacJ.jpg",
                "release_date": "2001-11-16T03:00:00.000Z",
                "vote_average": 7.8,
                "release_year": 2001,
                "release_month": 11,
                "release_day": 16,
                "link": "/latino/pelicula-completa/2001/harry-potter-y-la-piedra-filosofal/",
                "index": 24,
                "total": 24,
                "isFirst": false,
                "isLast": true
            }
        ],
        "movie": {
            "id": 5,
            "title": "Los increibles 2",
            "overview": "Helen debe liderar una campaña a fin de que los superhéroes retornen, mientras que Bob vive su vida \"normal\" con Violet, Dash y el bebé Jack-Jack. Su misión se marcha a pique cuando aparece un nuevo villano con un refulgente plan que lo amenaza todo. Mas los Parr no se asustarán y menos teniendo a Frozono de su parte.",
            "original_title": "Incredibles 2",
            "tagline": "Back to work.",
            "popularity": 120.785,
            "poster_path": "/x1txcDXkcM65gl7w20PwYSxAYah.jpg",
            "backdrop_path": "/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg",
            "runtime": 118,
            "budget": 200000000,
            "revenue": 868429911,
            "adult": 0,
            "imdb_id": "tt3606756",
            "facebook_id": "PixarTheIncredibles",
            "instagram_id": "TheIncredibles",
            "twitter_id": "TheIncredibles",
            "homepage": "https://movies.disney.com/incredibles-2",
            "vote_count": 3578,
            "vote_average": 7.6,
            "movie_status_id": 1,
            "release_date": "2018-06-14T03:00:00.000Z",
            "release_year": 2018,
            "release_month": 6,
            "release_day": 14,
            "genres": [{
                    "id": 1,
                    "name": "Acción",
                    "hash": "accion",
                    "link": "/categoria/accion/",
                    "index": 1,
                    "total": 4,
                    "isFirst": true,
                    "isLast": false
                },
                {
                    "id": 2,
                    "name": "Aventura",
                    "hash": "aventura",
                    "link": "/categoria/aventura/",
                    "index": 2,
                    "total": 4,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "id": 3,
                    "name": "Animación",
                    "hash": "animacion",
                    "link": "/categoria/animacion/",
                    "index": 3,
                    "total": 4,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "id": 8,
                    "name": "Familia",
                    "hash": "familia",
                    "link": "/categoria/familia/",
                    "index": 4,
                    "total": 4,
                    "isFirst": false,
                    "isLast": true
                }
            ],
            "videos": [{
                    "language_name": "English",
                    "language_iso": "en",
                    "name": "Incredibles 2 Official Teaser Trailer",
                    "site": "YouTube",
                    "key": "ZJDMWVZta3M",
                    "size": 1080,
                    "type": "Teaser",
                    "index": 1,
                    "total": 3,
                    "isFirst": true,
                    "isLast": false
                },
                {
                    "language_name": "English",
                    "language_iso": "en",
                    "name": "Incredibles 2 - Olympics Sneak Peek",
                    "site": "YouTube",
                    "key": "YBpdL9hSac4",
                    "size": 1080,
                    "type": "Featurette",
                    "index": 2,
                    "total": 3,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "language_name": "English",
                    "language_iso": "en",
                    "name": "Incredibles 2 Official Trailer",
                    "site": "YouTube",
                    "key": "i5qOzqD9Rms",
                    "size": 720,
                    "type": "Trailer",
                    "index": 3,
                    "total": 3,
                    "isFirst": false,
                    "isLast": true
                }
            ],
            "related_movies": [{
                    "hash": "animales-fantasticos-los-crimenes-de-grindelwald",
                    "title": "Animales fantásticos: Los crímenes de Grindelwald",
                    "overview": "Al final de la primera película, el poderoso mago obscuro Gellert Grindelwald (Johnny Depp) fue capturado por MACUSA (Congreso Mágico de los U.S.A. de América), con la ayuda de Newt Scamander (Eddie Redmayne). Mas, cumpliendo con su amenaza, Grindelwald escapó de su custodia y ha empezado a reunir seguidores, la mayor parte de los que no sospechan sus auténticas intenciones: levantar a los magos purasangre para reinar sobre todas y cada una de las criaturas no mágicas. En un sacrificio por frustrar los planes de Grindelwald, Albus Dumbledore (Jude Law) recluta a su viejo estudiante Newt Scamander, quien accede a prestar su ayuda, sin conocer los riesgos que esperan. Las líneas quedan marcadas mientras que el amor y la fidelidad son puestos a prueba, aun entre los amigos más próximos y la familia, en un planeta mágico poco a poco más dividido.",
                    "poster_path": "/uyJgTzAsp3Za2TaPiZt2yaKYRIR.jpg",
                    "release_date": "2018-11-14T03:00:00.000Z",
                    "vote_average": 7.4,
                    "release_year": 2018,
                    "release_month": 11,
                    "release_day": 14,
                    "link": "/latino/pelicula-completa/2018/animales-fantasticos-los-crimenes-de-grindelwald/",
                    "index": 1,
                    "total": 6,
                    "isFirst": true,
                    "isLast": false
                },
                {
                    "hash": "el-depredador",
                    "title": "El depredador",
                    "overview": "Desde los límites del espacio hasta los suburbios de las pequeñas urbes, la busca llega a la casa de la reinvención por Shane Black de la saga \"Predator\". Ahora, los cazadores más mortales del cosmos son más fuertes, más inteligentes y más mortales que jamás, y se han mejorado genéticamente con ADN de otras especies. En el momento en que un pequeño accidentariamente desencadena su regreso a la Tierra, solo un conjunto de ex- soldados y una maestra de ciencias van a poder eludir, quizás el fin de la raza humana...",
                    "poster_path": "/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg",
                    "release_date": "2018-09-13T03:00:00.000Z",
                    "vote_average": 5.3,
                    "release_year": 2018,
                    "release_month": 9,
                    "release_day": 13,
                    "link": "/latino/pelicula-completa/2018/el-depredador/",
                    "index": 2,
                    "total": 6,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "hash": "the-seven-deadly-sins-prisioneros-del-cielo",
                    "title": "The Seven Deadly Sins: Prisioneros del Cielo",
                    "overview": "Viajando en busca del ingrediente extraño, \"pez cielo\" Meliodas y Hawk llegan a un palacio que flota sobre las nubes. La gente de allá está ocupada preparando una liturgia, destinada a resguardar su hogar de una fiero bestia que se lúcida una vez cada tres mil años. Mas antes que se complete el ritual, los 6 Caballeros de Negro, un ejército del Clan Diablo, quitan el sello a la bestia y conminan la vida de todos en el Palacio del Cielo.",
                    "poster_path": "/lgYGPujZNckyKwQQNwMLmkWoKui.jpg",
                    "release_date": "2018-08-18T03:00:00.000Z",
                    "vote_average": 5.6,
                    "release_year": 2018,
                    "release_month": 8,
                    "release_day": 18,
                    "link": "/latino/pelicula-completa/2018/the-seven-deadly-sins-prisioneros-del-cielo/",
                    "index": 3,
                    "total": 6,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "hash": "megalodon",
                    "title": "Megalodón",
                    "overview": "Un sumergible de aguas profundas que es parte de un programa internacional de vigilancia submarina, ha sido atacado por una gran criatura que se creía extinta. Ahora está estropeado en el fondo de la fosa oceánica más profunda del Pacífico con su tripulación atrapada en el interior. El tiempo se termina y, contra los deseos de su hija Suyin (Li Bingbing), un soñador oceanógrafo chino (Winston Adiós) contrata a Jonas Taylor (Jason Statham), un especialista en rescate en aguas profundas. Su misión va a ser salvar a la tripulación y asimismo al océano de una amenaza imparable: un tiburón prehistórico de veintitres metros conocido con el nombre de Megalodón.",
                    "poster_path": "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
                    "release_date": "2018-08-09T03:00:00.000Z",
                    "vote_average": 6,
                    "release_year": 2018,
                    "release_month": 8,
                    "release_day": 9,
                    "link": "/latino/pelicula-completa/2018/megalodon/",
                    "index": 4,
                    "total": 6,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "hash": "el-justiciero-2",
                    "title": "El justiciero 2",
                    "overview": "Robert McCall,  hace justicia a los explotados y oprimidos, mas ahora se embarca en una infatigable busca de venganza por el planeta cuando se entera de que asesinaron a una novia que tuvo hace mucho.",
                    "poster_path": "/cQvc9N6JiMVKqol3wcYrGshsIdZ.jpg",
                    "release_date": "2018-07-19T03:00:00.000Z",
                    "vote_average": 6.2,
                    "release_year": 2018,
                    "release_month": 7,
                    "release_day": 19,
                    "link": "/latino/pelicula-completa/2018/el-justiciero-2/",
                    "index": 5,
                    "total": 6,
                    "isFirst": false,
                    "isLast": false
                },
                {
                    "hash": "vengadores-infinity-war",
                    "title": "Vengadores: Infinity War",
                    "overview": "El todopoderoso Thanos ha despertado con la promesa de arrasar con todo a su paso, portando el Guantelete del Infinito, que le proporciona un poder inestimable. Los únicos capaces de pararle los pies son los Vengadores y el resto de superhéroes de la galaxia, que habrán de estar prestos a sacrificarlo todo por un bien mayor.",
                    "poster_path": "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                    "release_date": "2018-04-25T03:00:00.000Z",
                    "vote_average": 8.3,
                    "release_year": 2018,
                    "release_month": 4,
                    "release_day": 25,
                    "link": "/latino/pelicula-completa/2018/vengadores-infinity-war/",
                    "index": 6,
                    "total": 6,
                    "isFirst": false,
                    "isLast": true
                }
            ]
        },
        "current_path": "/latino/pelicula-completa/2018/los-increibles-2/"
    };

    return next();
}